"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-probe-gate-contract", "preflight-probe-gate")
graph.connect("preflight-probe-gate", "prepare-probe-gate", label="prepared inputs")
graph.connect("prepare-probe-gate", "run-probe-gate", kind="data", label="action result")
graph.connect("run-probe-gate", "collect-probe-gate")
graph.connect("collect-probe-gate", "close-probe-gate")
graph.connect("close-probe-gate", "prepare-probe-gate", kind="loop", label="next cycle")
graph.connect("close-probe-gate", "finalize-probe-gate", kind="condition", label="completed")


@graph.step(
    "validate-probe-gate-contract",
    title="Validate probe matrix contract",
    phase="before_all",
    inputs=[],
    outputs=["contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-probe-gate-contract")
def node_validate_probe_gate_contract(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-probe-gate-contract", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_slo_drift_monitor_validate_probe_gate_contract",
            node_id="validate-probe-gate-contract",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-probe-gate-contract", outputs)


@graph.step(
    "preflight-probe-gate",
    title="Check probe matrix readiness",
    phase="before_all",
    inputs=["contract"],
    outputs=["preflight"],
    description=None,
)
@runner.phase("before_all", step_id="preflight-probe-gate")
def node_preflight_probe_gate(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("preflight-probe-gate", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_slo_drift_monitor_preflight_probe_gate",
            node_id="preflight-probe-gate",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("preflight-probe-gate", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_probe_gate_contract(ctx)
    node_preflight_probe_gate(ctx)


@graph.step(
    "prepare-probe-gate",
    title="Prepare probe matrix",
    phase="before_each",
    inputs=["preflight"],
    outputs=["prepared"],
    description=None,
)
@runner.phase("before_each", step_id="prepare-probe-gate")
def node_prepare_probe_gate(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("prepare-probe-gate", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_slo_drift_monitor_prepare_probe_gate",
            node_id="prepare-probe-gate",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("prepare-probe-gate", outputs)


@runner.phase("before_each")
def phase_before_each(ctx):
    node_prepare_probe_gate(ctx)


@graph.step(
    "run-probe-gate",
    title="Run probe matrix",
    phase="execute",
    inputs=["prepared"],
    outputs=["result"],
    description=None,
)
@runner.phase("execute", step_id="run-probe-gate")
def node_run_probe_gate(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("run-probe-gate", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_slo_drift_monitor_run_probe_gate",
            node_id="run-probe-gate",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("run-probe-gate", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_run_probe_gate(ctx)


@graph.step(
    "collect-probe-gate",
    title="Collect probe matrix evidence",
    phase="verify",
    inputs=["result"],
    outputs=["evidence"],
    description=None,
)
@runner.phase("verify", step_id="collect-probe-gate")
def node_collect_probe_gate(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("collect-probe-gate", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_slo_drift_monitor_collect_probe_gate",
            node_id="collect-probe-gate",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("collect-probe-gate", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_collect_probe_gate(ctx)


@graph.step(
    "close-probe-gate",
    title="Close probe matrix cycle",
    phase="after_each",
    inputs=["evidence"],
    outputs=["complete"],
    description=None,
)
@runner.phase("after_each", step_id="close-probe-gate")
def node_close_probe_gate(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("close-probe-gate", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_slo_drift_monitor_close_probe_gate",
            node_id="close-probe-gate",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("close-probe-gate", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    node_close_probe_gate(ctx)


@graph.step(
    "finalize-probe-gate",
    title="Finalize probe matrix",
    phase="after_all",
    inputs=["complete"],
    outputs=["final"],
    description=None,
)
@runner.phase("after_all", step_id="finalize-probe-gate")
def node_finalize_probe_gate(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize-probe-gate", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_slo_drift_monitor_finalize_probe_gate",
            node_id="finalize-probe-gate",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize-probe-gate", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_finalize_probe_gate(ctx)


if __name__ == "__main__":
    runner.main()
