"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-user-journey-runtime", "validate-user-journey")
graph.connect("validate-user-journey", "load-user-journey-state")
graph.connect("load-user-journey-state", "plan-user-journey")
graph.connect("plan-user-journey", "run-user-journey", label="focused cases")
graph.connect("run-user-journey", "review-user-journey", kind="data", label="browser evidence")
graph.connect("review-user-journey", "retain-user-journey")
graph.connect("retain-user-journey", "plan-user-journey", kind="loop", label="next iteration")
graph.connect("retain-user-journey", "finalize-user-journey", kind="condition", label="completed")


@graph.step(
    "validate-user-journey-runtime",
    title="Validate user journey runtime",
    phase="before_all",
    inputs=[],
    outputs=["browser_runtime"],
    description=None,
)
@runner.phase("before_all", step_id="validate-user-journey-runtime")
def node_validate_user_journey_runtime(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-user-journey-runtime", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_user_journey_cycle_validate_user_journey_runtime",
            node_id="validate-user-journey-runtime",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-user-journey-runtime", outputs)


@graph.step(
    "validate-user-journey",
    title="Validate user journey contract",
    phase="before_all",
    inputs=["browser_runtime"],
    outputs=["journey_contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-user-journey")
def node_validate_user_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-user-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_user_journey_cycle_validate_user_journey",
            node_id="validate-user-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-user-journey", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_user_journey_runtime(ctx)
    node_validate_user_journey(ctx)


@graph.step(
    "load-user-journey-state",
    title="Load user journey state",
    phase="before_each",
    inputs=["journey_contract"],
    outputs=["journey_state"],
    description=None,
)
@runner.phase("before_each", step_id="load-user-journey-state")
def node_load_user_journey_state(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("load-user-journey-state", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_user_journey_cycle_load_user_journey_state",
            node_id="load-user-journey-state",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("load-user-journey-state", outputs)


@graph.step(
    "plan-user-journey",
    title="Plan focused user journey",
    phase="before_each",
    inputs=["journey_state"],
    outputs=["journey_plan"],
    description=None,
)
@runner.phase("before_each", step_id="plan-user-journey")
def node_plan_user_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("plan-user-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_user_journey_cycle_plan_user_journey",
            node_id="plan-user-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("plan-user-journey", outputs)


@runner.phase("before_each")
def phase_before_each(ctx):
    node_load_user_journey_state(ctx)
    node_plan_user_journey(ctx)


@graph.step(
    "run-user-journey",
    title="Run user journey",
    phase="execute",
    inputs=["journey_plan"],
    outputs=["journey_evidence"],
    description=None,
)
@runner.phase("execute", step_id="run-user-journey")
def node_run_user_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("run-user-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_user_journey_cycle_run_user_journey",
            node_id="run-user-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("run-user-journey", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_run_user_journey(ctx)


@graph.step(
    "review-user-journey",
    title="Review user journey evidence",
    phase="verify",
    inputs=["journey_evidence"],
    outputs=["journey_handoff"],
    description=None,
)
@runner.phase("verify", step_id="review-user-journey")
def node_review_user_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("review-user-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_user_journey_cycle_review_user_journey",
            node_id="review-user-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("review-user-journey", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_review_user_journey(ctx)


@graph.step(
    "retain-user-journey",
    title="Retain user journey result",
    phase="after_each",
    inputs=["journey_handoff"],
    outputs=["iteration_complete"],
    description=None,
)
@runner.phase("after_each", step_id="retain-user-journey")
def node_retain_user_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("retain-user-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_user_journey_cycle_retain_user_journey",
            node_id="retain-user-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("retain-user-journey", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    node_retain_user_journey(ctx)


@graph.step(
    "finalize-user-journey",
    title="Finalize user journey evaluation",
    phase="after_all",
    inputs=["iteration_complete"],
    outputs=["final_status"],
    description=None,
)
@runner.phase("after_all", step_id="finalize-user-journey")
def node_finalize_user_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize-user-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_user_journey_cycle_finalize_user_journey",
            node_id="finalize-user-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize-user-journey", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_finalize_user_journey(ctx)


if __name__ == "__main__":
    runner.main()
