"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-critical-flow-runtime", "validate-critical-flow")
graph.connect("validate-critical-flow", "load-critical-flow-state")
graph.connect("load-critical-flow-state", "plan-critical-flow")
graph.connect("plan-critical-flow", "run-critical-flow", label="focused cases")
graph.connect("run-critical-flow", "review-critical-flow", kind="data", label="browser evidence")
graph.connect("review-critical-flow", "retain-critical-flow")
graph.connect("retain-critical-flow", "plan-critical-flow", kind="loop", label="next iteration")
graph.connect("retain-critical-flow", "finalize-critical-flow", kind="condition", label="completed")


@graph.step(
    "validate-critical-flow-runtime",
    title="Validate critical flow runtime",
    phase="before_all",
    inputs=[],
    outputs=["browser_runtime"],
    description=None,
)
@runner.phase("before_all", step_id="validate-critical-flow-runtime")
def node_validate_critical_flow_runtime(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-critical-flow-runtime", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_critical_flow_proof_validate_critical_flow_runtime",
            node_id="validate-critical-flow-runtime",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-critical-flow-runtime", outputs)


@graph.step(
    "validate-critical-flow",
    title="Validate critical flow contract",
    phase="before_all",
    inputs=["browser_runtime"],
    outputs=["journey_contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-critical-flow")
def node_validate_critical_flow(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-critical-flow", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_critical_flow_proof_validate_critical_flow",
            node_id="validate-critical-flow",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-critical-flow", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_critical_flow_runtime(ctx)
    node_validate_critical_flow(ctx)


@graph.step(
    "load-critical-flow-state",
    title="Load critical flow state",
    phase="before_each",
    inputs=["journey_contract"],
    outputs=["journey_state"],
    description=None,
)
@runner.phase("before_each", step_id="load-critical-flow-state")
def node_load_critical_flow_state(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("load-critical-flow-state", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_critical_flow_proof_load_critical_flow_state",
            node_id="load-critical-flow-state",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("load-critical-flow-state", outputs)


@graph.step(
    "plan-critical-flow",
    title="Plan focused critical flow",
    phase="before_each",
    inputs=["journey_state"],
    outputs=["journey_plan"],
    description=None,
)
@runner.phase("before_each", step_id="plan-critical-flow")
def node_plan_critical_flow(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("plan-critical-flow", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_critical_flow_proof_plan_critical_flow",
            node_id="plan-critical-flow",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("plan-critical-flow", outputs)


@runner.phase("before_each")
def phase_before_each(ctx):
    node_load_critical_flow_state(ctx)
    node_plan_critical_flow(ctx)


@graph.step(
    "run-critical-flow",
    title="Run critical flow",
    phase="execute",
    inputs=["journey_plan"],
    outputs=["journey_evidence"],
    description=None,
)
@runner.phase("execute", step_id="run-critical-flow")
def node_run_critical_flow(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("run-critical-flow", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_critical_flow_proof_run_critical_flow",
            node_id="run-critical-flow",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("run-critical-flow", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_run_critical_flow(ctx)


@graph.step(
    "review-critical-flow",
    title="Review critical flow evidence",
    phase="verify",
    inputs=["journey_evidence"],
    outputs=["journey_handoff"],
    description=None,
)
@runner.phase("verify", step_id="review-critical-flow")
def node_review_critical_flow(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("review-critical-flow", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_critical_flow_proof_review_critical_flow",
            node_id="review-critical-flow",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("review-critical-flow", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_review_critical_flow(ctx)


@graph.step(
    "retain-critical-flow",
    title="Retain critical flow result",
    phase="after_each",
    inputs=["journey_handoff"],
    outputs=["iteration_complete"],
    description=None,
)
@runner.phase("after_each", step_id="retain-critical-flow")
def node_retain_critical_flow(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("retain-critical-flow", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_critical_flow_proof_retain_critical_flow",
            node_id="retain-critical-flow",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("retain-critical-flow", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    node_retain_critical_flow(ctx)


@graph.step(
    "finalize-critical-flow",
    title="Finalize critical flow evaluation",
    phase="after_all",
    inputs=["iteration_complete"],
    outputs=["final_status"],
    description=None,
)
@runner.phase("after_all", step_id="finalize-critical-flow")
def node_finalize_critical_flow(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize-critical-flow", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_critical_flow_proof_finalize_critical_flow",
            node_id="finalize-critical-flow",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize-critical-flow", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_finalize_critical_flow(ctx)


if __name__ == "__main__":
    runner.main()
