"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-browser-runtime", "validate")
graph.connect("validate", "observe")
graph.connect("observe", "decide", kind="data", label="rendered choices")
graph.connect("decide", "act", kind="data", label="one safe action")
graph.connect("act", "reflect", kind="data", label="action evidence")
graph.connect("reflect", "observe", kind="loop", label="next visit")
graph.connect("reflect", "finalize", kind="condition", label="completed")


@graph.step(
    "validate-browser-runtime",
    title="Validate persona browser runtime",
    phase="before_all",
    inputs=[],
    outputs=["browser_target"],
    description=None,
)
@runner.phase("before_all", step_id="validate-browser-runtime")
def node_validate_browser_runtime(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-browser-runtime", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_continuous_user_journey_validate_browser_runtime",
            node_id="validate-browser-runtime",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-browser-runtime", outputs)


@graph.step(
    "validate",
    title="Validate autonomous persona contract",
    phase="before_all",
    inputs=["browser_target"],
    outputs=["persona_contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate")
def validate(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_continuous_user_journey_validate",
            node_id="validate",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_browser_runtime(ctx)
    validate(ctx)


@graph.step(
    "observe",
    title="Observe current page",
    phase="before_each",
    inputs=["persona_contract"],
    outputs=["page_choices"],
    description=None,
)
@runner.phase("before_each", step_id="observe")
def observe(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("observe", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_continuous_user_journey_observe",
            node_id="observe",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("observe", outputs)


@runner.phase("before_each")
def phase_before_each(ctx):
    observe(ctx)


@graph.step(
    "decide",
    title="Plan next persona action",
    phase="execute",
    inputs=["page_choices"],
    outputs=["persona_plan"],
    description=None,
)
@runner.phase("execute", step_id="decide")
def decide(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("decide", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_continuous_user_journey_decide",
            node_id="decide",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("decide", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    decide(ctx)


@graph.step(
    "act",
    title="Take one safe persona action",
    phase="verify",
    inputs=["persona_plan"],
    outputs=["action_evidence"],
    description=None,
)
@runner.phase("verify", step_id="act")
def act(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("act", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_continuous_user_journey_act",
            node_id="act",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("act", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    act(ctx)


@graph.step(
    "reflect",
    title="Reflect persona session",
    phase="after_each",
    inputs=["action_evidence"],
    outputs=["persona_handoff"],
    description=None,
)
@runner.phase("after_each", step_id="reflect")
def reflect(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("reflect", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_continuous_user_journey_reflect",
            node_id="reflect",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("reflect", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    reflect(ctx)


@graph.step(
    "finalize",
    title="Finalize autonomous persona",
    phase="after_all",
    inputs=["persona_handoff"],
    outputs=["final_status"],
    description=None,
)
@runner.phase("after_all", step_id="finalize")
def finalize(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_continuous_user_journey_finalize",
            node_id="finalize",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    finalize(ctx)


if __name__ == "__main__":
    runner.main()
