"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-source-contract", "run-browser-journey")
graph.connect("run-browser-journey", "publish-rendered-evidence", kind="data", label="browser evidence")
graph.connect("publish-rendered-evidence", "close-source-aware-cycle")
graph.connect("close-source-aware-cycle", "run-browser-journey", kind="loop", label="next iteration")
graph.connect(
    "close-source-aware-cycle", "finalize-source-aware-journey", kind="condition", label="completed"
)


@graph.step(
    "validate-source-contract",
    title="Validate source and browser contract",
    phase="before_all",
    inputs=[],
    outputs=["source_contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-source-contract")
def node_validate_source_contract(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-source-contract", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_source_aware_browser_journey_validate_source_contract",
            node_id="validate-source-contract",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-source-contract", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_source_contract(ctx)


@graph.step(
    "run-browser-journey",
    title="Run rendered browser journey",
    phase="execute",
    inputs=["source_contract"],
    outputs=["browser_evidence"],
    description=None,
)
@runner.phase("execute", step_id="run-browser-journey")
def node_run_browser_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("run-browser-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_source_aware_browser_journey_run_browser_journey",
            node_id="run-browser-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("run-browser-journey", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_run_browser_journey(ctx)


@graph.step(
    "publish-rendered-evidence",
    title="Publish rendered evidence",
    phase="verify",
    inputs=["browser_evidence"],
    outputs=["review_ready"],
    description=None,
)
@runner.phase("verify", step_id="publish-rendered-evidence")
def node_publish_rendered_evidence(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("publish-rendered-evidence", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_source_aware_browser_journey_publish_rendered_evidence",
            node_id="publish-rendered-evidence",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("publish-rendered-evidence", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_publish_rendered_evidence(ctx)


@graph.step(
    "close-source-aware-cycle",
    title="Close source-aware browser cycle",
    phase="after_each",
    inputs=["review_ready"],
    outputs=["cycle_complete"],
    description=None,
)
@runner.phase("after_each", step_id="close-source-aware-cycle")
def node_close_source_aware_cycle(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("close-source-aware-cycle", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_source_aware_browser_journey_close_source_aware_cycle",
            node_id="close-source-aware-cycle",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("close-source-aware-cycle", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    node_close_source_aware_cycle(ctx)


@graph.step(
    "finalize-source-aware-journey",
    title="Finalize source-aware browser journey",
    phase="after_all",
    inputs=["cycle_complete"],
    outputs=["journey_complete"],
    description=None,
)
@runner.phase("after_all", step_id="finalize-source-aware-journey")
def node_finalize_source_aware_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize-source-aware-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_source_aware_browser_journey_finalize_source_aware_journey",
            node_id="finalize-source-aware-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize-source-aware-journey", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_finalize_source_aware_journey(ctx)


if __name__ == "__main__":
    runner.main()
