"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-adapter-contract", "check-adapter")
graph.connect("check-adapter", "prepare-adapter", label="prepared target")
graph.connect("prepare-adapter", "run-adapter", kind="data", label="adapter output")
graph.connect("run-adapter", "collect-adapter-evidence")
graph.connect("collect-adapter-evidence", "close-adapter-cycle")
graph.connect("close-adapter-cycle", "prepare-adapter", kind="loop", label="next cycle")
graph.connect("close-adapter-cycle", "finalize-adapter", kind="condition", label="completed")


@graph.step(
    "validate-adapter-contract",
    title="Validate adapter command",
    phase="before_all",
    inputs=[],
    outputs=["adapter_contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-adapter-contract")
def node_validate_adapter_contract(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-adapter-contract", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_external_command_adapter_validate_adapter_contract",
            node_id="validate-adapter-contract",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-adapter-contract", outputs)


@graph.step(
    "check-adapter",
    title="Check adapter readiness",
    phase="before_all",
    inputs=["adapter_contract"],
    outputs=["adapter_status"],
    description=None,
)
@runner.phase("before_all", step_id="check-adapter")
def node_check_adapter(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("check-adapter", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_external_command_adapter_check_adapter",
            node_id="check-adapter",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("check-adapter", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_adapter_contract(ctx)
    node_check_adapter(ctx)


@graph.step(
    "prepare-adapter",
    title="Prepare adapter cycle",
    phase="before_each",
    inputs=["adapter_status"],
    outputs=["prepared_target"],
    description=None,
)
@runner.phase("before_each", step_id="prepare-adapter")
def node_prepare_adapter(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("prepare-adapter", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_external_command_adapter_prepare_adapter",
            node_id="prepare-adapter",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("prepare-adapter", outputs)


@runner.phase("before_each")
def phase_before_each(ctx):
    node_prepare_adapter(ctx)


@graph.step(
    "run-adapter",
    title="Run bounded adapter task",
    phase="execute",
    inputs=["prepared_target"],
    outputs=["adapter_result"],
    description=None,
)
@runner.phase("execute", step_id="run-adapter")
def node_run_adapter(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("run-adapter", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_external_command_adapter_run_adapter",
            node_id="run-adapter",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("run-adapter", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_run_adapter(ctx)


@graph.step(
    "collect-adapter-evidence",
    title="Collect adapter evidence",
    phase="verify",
    inputs=["adapter_result"],
    outputs=["adapter_evidence"],
    description=None,
)
@runner.phase("verify", step_id="collect-adapter-evidence")
def node_collect_adapter_evidence(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("collect-adapter-evidence", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_external_command_adapter_collect_adapter_evidence",
            node_id="collect-adapter-evidence",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("collect-adapter-evidence", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_collect_adapter_evidence(ctx)


@graph.step(
    "close-adapter-cycle",
    title="Close adapter cycle",
    phase="after_each",
    inputs=["adapter_evidence"],
    outputs=["cycle_complete"],
    description=None,
)
@runner.phase("after_each", step_id="close-adapter-cycle")
def node_close_adapter_cycle(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("close-adapter-cycle", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_external_command_adapter_close_adapter_cycle",
            node_id="close-adapter-cycle",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("close-adapter-cycle", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    node_close_adapter_cycle(ctx)


@graph.step(
    "finalize-adapter",
    title="Finalize external automation",
    phase="after_all",
    inputs=["cycle_complete"],
    outputs=["final_status"],
    description=None,
)
@runner.phase("after_all", step_id="finalize-adapter")
def node_finalize_adapter(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize-adapter", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_external_command_adapter_finalize_adapter",
            node_id="finalize-adapter",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize-adapter", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_finalize_adapter(ctx)


if __name__ == "__main__":
    runner.main()
