"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-target", "validate-evaluation-inputs")
graph.connect("validate-evaluation-inputs", "prepare-prompt")
graph.connect("prepare-prompt", "exercise-target", label="managed prompt")
graph.connect("exercise-target", "retain-iteration", kind="data", label="responses")
graph.connect("retain-iteration", "propose-agent-change", label="supervisor assessment")
graph.connect("propose-agent-change", "prepare-prompt", kind="loop", label="next evaluation")


@graph.step(
    "validate-target",
    title="Validate target repository",
    phase="before_all",
    inputs=[],
    outputs=["repository_target"],
    description=None,
)
@runner.phase("before_all", step_id="validate-target")
def node_validate_target(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-target", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_agent_self_improvement_validate_target",
            node_id="validate-target",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-target", outputs)


@graph.step(
    "validate-evaluation-inputs",
    title="Validate evaluation inputs",
    phase="before_all",
    inputs=["repository_target"],
    outputs=["evaluation_contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-evaluation-inputs")
def node_validate_evaluation_inputs(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-evaluation-inputs", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_agent_self_improvement_validate_evaluation_inputs",
            node_id="validate-evaluation-inputs",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-evaluation-inputs", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_target(ctx)
    node_validate_evaluation_inputs(ctx)


@graph.step(
    "prepare-prompt",
    title="Read change target",
    phase="before_each",
    inputs=["evaluation_contract"],
    outputs=["managed_prompt"],
    description=None,
)
@runner.phase("before_each", step_id="prepare-prompt")
def node_prepare_prompt(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("prepare-prompt", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_agent_self_improvement_prepare_prompt",
            node_id="prepare-prompt",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("prepare-prompt", outputs)


@runner.phase("before_each")
def phase_before_each(ctx):
    node_prepare_prompt(ctx)


@graph.step(
    "exercise-target",
    title="Exercise target AI",
    phase="execute",
    inputs=["managed_prompt"],
    outputs=["target_responses"],
    description=None,
)
@runner.phase("execute", step_id="exercise-target")
def node_exercise_target(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("exercise-target", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_agent_self_improvement_exercise_target",
            node_id="exercise-target",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("exercise-target", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_exercise_target(ctx)


@graph.step(
    "retain-iteration",
    title="Retain assessment evidence",
    phase="after_each",
    inputs=["target_responses"],
    outputs=["iteration_snapshot"],
    description=None,
)
@runner.phase("after_each", step_id="retain-iteration")
def node_retain_iteration(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("retain-iteration", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_agent_self_improvement_retain_iteration",
            node_id="retain-iteration",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("retain-iteration", outputs)


@graph.step(
    "propose-agent-change",
    title="Create agent proposal for assessed issue",
    phase="after_each",
    inputs=["iteration_snapshot"],
    outputs=["agent_proposal"],
    description=None,
)
@runner.phase("after_each", step_id="propose-agent-change")
def node_propose_agent_change(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("propose-agent-change", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_agent_self_improvement_propose_agent_change",
            node_id="propose-agent-change",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("propose-agent-change", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    node_retain_iteration(ctx)
    node_propose_agent_change(ctx)


if __name__ == "__main__":
    runner.main()
