"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-browser-runtime", "validate-browser-journey")
graph.connect("validate-browser-journey", "run-browser-journey")
graph.connect("run-browser-journey", "verify-browser-evidence", kind="data", label="journey evidence")
graph.connect("verify-browser-evidence", "finalize-browser-evaluation")


@graph.step(
    "validate-browser-runtime",
    title="Validate browser runtime",
    phase="before_all",
    inputs=[],
    outputs=["browser_target"],
    description=None,
)
@runner.phase("before_all", step_id="validate-browser-runtime")
def node_validate_browser_runtime(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-browser-runtime", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_user_journey_smoke_test_validate_browser_runtime",
            node_id="validate-browser-runtime",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-browser-runtime", outputs)


@graph.step(
    "validate-browser-journey",
    title="Validate browser journey contract",
    phase="before_all",
    inputs=["browser_target"],
    outputs=["journey_contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-browser-journey")
def node_validate_browser_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-browser-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_user_journey_smoke_test_validate_browser_journey",
            node_id="validate-browser-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-browser-journey", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_browser_runtime(ctx)
    node_validate_browser_journey(ctx)


@graph.step(
    "run-browser-journey",
    title="Run browser journey",
    phase="execute",
    inputs=["journey_contract"],
    outputs=["journey_evidence"],
    description=None,
)
@runner.phase("execute", step_id="run-browser-journey")
def node_run_browser_journey(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("run-browser-journey", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_user_journey_smoke_test_run_browser_journey",
            node_id="run-browser-journey",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("run-browser-journey", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_run_browser_journey(ctx)


@graph.step(
    "verify-browser-evidence",
    title="Verify journey evidence",
    phase="verify",
    inputs=["journey_evidence"],
    outputs=["journey_verdict"],
    description=None,
)
@runner.phase("verify", step_id="verify-browser-evidence")
def node_verify_browser_evidence(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("verify-browser-evidence", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_user_journey_smoke_test_verify_browser_evidence",
            node_id="verify-browser-evidence",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("verify-browser-evidence", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_verify_browser_evidence(ctx)


@graph.step(
    "finalize-browser-evaluation",
    title="Finalize browser evaluation",
    phase="after_all",
    inputs=["journey_verdict"],
    outputs=["completed_evaluation"],
    description=None,
)
@runner.phase("after_all", step_id="finalize-browser-evaluation")
def node_finalize_browser_evaluation(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize-browser-evaluation", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_user_journey_smoke_test_finalize_browser_evaluation",
            node_id="finalize-browser-evaluation",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize-browser-evaluation", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_finalize_browser_evaluation(ctx)


if __name__ == "__main__":
    runner.main()
