"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-site", "explore-site")
graph.connect("explore-site", "review-evidence", kind="data", label="rendered pages")
graph.connect("review-evidence", "finalize-review")


@graph.step(
    "validate-site",
    title="Validate site",
    phase="before_all",
    inputs=[],
    outputs=["site_target"],
    description=None,
)
@runner.phase("before_all", step_id="validate-site")
def node_validate_site(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-site", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_site_exploration_review_validate_site",
            node_id="validate-site",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-site", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_site(ctx)


@graph.step(
    "explore-site",
    title="Explore rendered site",
    phase="execute",
    inputs=["site_target"],
    outputs=["rendered_pages"],
    description=None,
)
@runner.phase("execute", step_id="explore-site")
def node_explore_site(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("explore-site", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_site_exploration_review_explore_site",
            node_id="explore-site",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("explore-site", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_explore_site(ctx)


@graph.step(
    "review-evidence",
    title="Review exploration evidence",
    phase="verify",
    inputs=["rendered_pages"],
    outputs=["product_review"],
    description=None,
)
@runner.phase("verify", step_id="review-evidence")
def node_review_evidence(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("review-evidence", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_site_exploration_review_review_evidence",
            node_id="review-evidence",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("review-evidence", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_review_evidence(ctx)


@graph.step(
    "finalize-review",
    title="Finalize site review",
    phase="after_all",
    inputs=["product_review"],
    outputs=["completed_review"],
    description=None,
)
@runner.phase("after_all", step_id="finalize-review")
def node_finalize_review(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize-review", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_site_exploration_review_finalize_review",
            node_id="finalize-review",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize-review", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_finalize_review(ctx)


if __name__ == "__main__":
    runner.main()
