"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-target", "validate-evaluation-inputs")
graph.connect("validate-evaluation-inputs", "snapshot-baseline")
graph.connect("snapshot-baseline", "prepare-prompt")
graph.connect("prepare-prompt", "exercise-target", label="managed prompt")
graph.connect("exercise-target", "assess-candidate", kind="data", label="responses")
graph.connect("assess-candidate", "retain-iteration")
graph.connect("retain-iteration", "prepare-prompt", kind="loop", label="next evaluation")
graph.connect("retain-iteration", "restore-baseline", kind="condition", label="completed")


@graph.step(
    "validate-target",
    title="Validate target repository",
    phase="before_all",
    inputs=[],
    outputs=["repository_target"],
    description=None,
)
@runner.phase("before_all", step_id="validate-target")
def node_validate_target(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-target", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_native_improvement_cycle_validate_target",
            node_id="validate-target",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-target", outputs)


@graph.step(
    "validate-evaluation-inputs",
    title="Validate evaluation inputs",
    phase="before_all",
    inputs=["repository_target"],
    outputs=["evaluation_contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-evaluation-inputs")
def node_validate_evaluation_inputs(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-evaluation-inputs", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_native_improvement_cycle_validate_evaluation_inputs",
            node_id="validate-evaluation-inputs",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-evaluation-inputs", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_target(ctx)
    node_validate_evaluation_inputs(ctx)


@graph.step(
    "snapshot-baseline",
    title="Snapshot iteration baseline",
    phase="before_each",
    inputs=["evaluation_contract"],
    outputs=["baseline_snapshot"],
    description=None,
)
@runner.phase("before_each", step_id="snapshot-baseline")
def node_snapshot_baseline(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("snapshot-baseline", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_native_improvement_cycle_snapshot_baseline",
            node_id="snapshot-baseline",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("snapshot-baseline", outputs)


@graph.step(
    "prepare-prompt",
    title="Prepare prompt candidate",
    phase="before_each",
    inputs=["baseline_snapshot"],
    outputs=["managed_prompt"],
    description=None,
)
@runner.phase("before_each", step_id="prepare-prompt")
def node_prepare_prompt(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("prepare-prompt", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_native_improvement_cycle_prepare_prompt",
            node_id="prepare-prompt",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("prepare-prompt", outputs)


@runner.phase("before_each")
def phase_before_each(ctx):
    node_snapshot_baseline(ctx)
    node_prepare_prompt(ctx)


@graph.step(
    "exercise-target",
    title="Exercise target AI",
    phase="execute",
    inputs=["managed_prompt"],
    outputs=["target_responses"],
    description=None,
)
@runner.phase("execute", step_id="exercise-target")
def node_exercise_target(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("exercise-target", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_native_improvement_cycle_exercise_target",
            node_id="exercise-target",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("exercise-target", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_exercise_target(ctx)


@graph.step(
    "assess-candidate",
    title="Assess candidate evidence",
    phase="verify",
    inputs=["target_responses"],
    outputs=["candidate_verdict"],
    description=None,
)
@runner.phase("verify", step_id="assess-candidate")
def node_assess_candidate(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("assess-candidate", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_native_improvement_cycle_assess_candidate",
            node_id="assess-candidate",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("assess-candidate", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_assess_candidate(ctx)


@graph.step(
    "retain-iteration",
    title="Retain iteration evidence",
    phase="after_each",
    inputs=["candidate_verdict"],
    outputs=["iteration_snapshot"],
    description=None,
)
@runner.phase("after_each", step_id="retain-iteration")
def node_retain_iteration(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("retain-iteration", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_native_improvement_cycle_retain_iteration",
            node_id="retain-iteration",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("retain-iteration", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    node_retain_iteration(ctx)


@graph.step(
    "restore-baseline",
    title="Restore baseline",
    phase="after_all",
    inputs=["iteration_snapshot"],
    outputs=["restored_target"],
    description=None,
)
@runner.phase("after_all", step_id="restore-baseline")
def node_restore_baseline(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("restore-baseline", {})
    outputs.update(
        ctx.run_visual_node(
            "template_runner_templates_native_improvement_cycle_restore_baseline",
            node_id="restore-baseline",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("restore-baseline", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_restore_baseline(ctx)


if __name__ == "__main__":
    runner.main()
