"""Generated by OpenOrbit Visual Runner Editor. Do not edit by hand."""

from orbit_sdk import graph, runner

graph.connect("validate-agent-cycle-contract", "preflight-agent-cycle")
graph.connect("preflight-agent-cycle", "prepare-agent-cycle", label="prepared inputs")
graph.connect("prepare-agent-cycle", "run-agent-cycle", kind="data", label="action result")
graph.connect("run-agent-cycle", "collect-agent-cycle")
graph.connect("collect-agent-cycle", "close-agent-cycle")
graph.connect("close-agent-cycle", "prepare-agent-cycle", kind="loop", label="next cycle")
graph.connect("close-agent-cycle", "finalize-agent-cycle", kind="condition", label="completed")


@graph.step(
    "validate-agent-cycle-contract",
    title="Validate external agent contract",
    phase="before_all",
    inputs=[],
    outputs=["contract"],
    description=None,
)
@runner.phase("before_all", step_id="validate-agent-cycle-contract")
def node_validate_agent_cycle_contract(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("validate-agent-cycle-contract", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_experience_improvement_validate_agent_cycle_contract",
            node_id="validate-agent-cycle-contract",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("validate-agent-cycle-contract", outputs)


@graph.step(
    "preflight-agent-cycle",
    title="Check external agent readiness",
    phase="before_all",
    inputs=["contract"],
    outputs=["preflight"],
    description=None,
)
@runner.phase("before_all", step_id="preflight-agent-cycle")
def node_preflight_agent_cycle(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("preflight-agent-cycle", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_experience_improvement_preflight_agent_cycle",
            node_id="preflight-agent-cycle",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("preflight-agent-cycle", outputs)


@runner.phase("before_all")
def phase_before_all(ctx):
    node_validate_agent_cycle_contract(ctx)
    node_preflight_agent_cycle(ctx)


@graph.step(
    "prepare-agent-cycle",
    title="Prepare external agent",
    phase="before_each",
    inputs=["preflight"],
    outputs=["prepared"],
    description=None,
)
@runner.phase("before_each", step_id="prepare-agent-cycle")
def node_prepare_agent_cycle(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("prepare-agent-cycle", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_experience_improvement_prepare_agent_cycle",
            node_id="prepare-agent-cycle",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("prepare-agent-cycle", outputs)


@runner.phase("before_each")
def phase_before_each(ctx):
    node_prepare_agent_cycle(ctx)


@graph.step(
    "run-agent-cycle",
    title="Run external agent",
    phase="execute",
    inputs=["prepared"],
    outputs=["result"],
    description=None,
)
@runner.phase("execute", step_id="run-agent-cycle")
def node_run_agent_cycle(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("run-agent-cycle", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_experience_improvement_run_agent_cycle",
            node_id="run-agent-cycle",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("run-agent-cycle", outputs)


@runner.phase("execute")
def phase_execute(ctx):
    node_run_agent_cycle(ctx)


@graph.step(
    "collect-agent-cycle",
    title="Collect external agent evidence",
    phase="verify",
    inputs=["result"],
    outputs=["evidence"],
    description=None,
)
@runner.phase("verify", step_id="collect-agent-cycle")
def node_collect_agent_cycle(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("collect-agent-cycle", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_experience_improvement_collect_agent_cycle",
            node_id="collect-agent-cycle",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("collect-agent-cycle", outputs)


@runner.phase("verify")
def phase_verify(ctx):
    node_collect_agent_cycle(ctx)


@graph.step(
    "close-agent-cycle",
    title="Close external agent cycle",
    phase="after_each",
    inputs=["evidence"],
    outputs=["complete"],
    description=None,
)
@runner.phase("after_each", step_id="close-agent-cycle")
def node_close_agent_cycle(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("close-agent-cycle", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_experience_improvement_close_agent_cycle",
            node_id="close-agent-cycle",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("close-agent-cycle", outputs)


@runner.phase("after_each")
def phase_after_each(ctx):
    node_close_agent_cycle(ctx)


@graph.step(
    "finalize-agent-cycle",
    title="Finalize external agent",
    phase="after_all",
    inputs=["complete"],
    outputs=["final"],
    description=None,
)
@runner.phase("after_all", step_id="finalize-agent-cycle")
def node_finalize_agent_cycle(ctx):
    config = {}
    outputs = ctx.visual_node_inputs("finalize-agent-cycle", {})
    outputs.update(
        ctx.run_visual_node(
            "template_quick_starts_openorbit_ai_experience_improvement_finalize_agent_cycle",
            node_id="finalize-agent-cycle",
            config=config,
            inputs=outputs,
        )
    )
    ctx.publish_visual_node_outputs("finalize-agent-cycle", outputs)


@runner.phase("after_all")
def phase_after_all(ctx):
    node_finalize_agent_cycle(ctx)


if __name__ == "__main__":
    runner.main()
